// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $stories from "./routes/stories.tsx";
import * as $Button_story from "./islands/Button_story.tsx";
import * as $ColoredButton from "./islands/ColoredButton.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Counter_story from "./islands/Counter_story.tsx";
import * as $Footer_story from "./islands/Footer_story.tsx";
import * as $Header_story from "./islands/Header_story.tsx";
import * as $Hero_story from "./islands/Hero_story.tsx";
import * as $StoryFrame from "./islands/StoryFrame.tsx";
import * as $StoryList from "./islands/StoryList.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/stories.tsx": $stories,
  },
  islands: {
    "./islands/Button_story.tsx": $Button_story,
    "./islands/ColoredButton.tsx": $ColoredButton,
    "./islands/Counter.tsx": $Counter,
    "./islands/Counter_story.tsx": $Counter_story,
    "./islands/Footer_story.tsx": $Footer_story,
    "./islands/Header_story.tsx": $Header_story,
    "./islands/Hero_story.tsx": $Hero_story,
    "./islands/StoryFrame.tsx": $StoryFrame,
    "./islands/StoryList.tsx": $StoryList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
